### ISSUE TITLE
http://static.decontextualize.com/gutenberg-poetry-v001.ndjson.gz broken

### ISSUE THREAD

**Issue by thisismattmiller** [aparrish/gutenberg-poetry-corpus#3]
Looks like the corpus link http://static.decontextualize.com/gutenberg-poetry-v001.ndjson.gz is no longer working, is the corpus file available anywhere else? Thanks for building this!

**Comment by aparrish** [comment]
The link works for me—can you describe the issue you're having?

**Comment by thisismattmiller** [comment]
Oh sorry, it looks like it was just being block by chrome for https reasons:

```Mixed Content: The site at 'https://github.com/' was loaded over a secure connection, but the file at 'http://static.decontextualize.com/gutenberg-poetry-v001.ndjson.gz' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.```

When I copy the url and open it not as a link or use wget/curl it works. I should have tried that and didn't notice the console msg.

Thanks!
-Matt
